version: '2'

services:
  db:
    image: mysql/mysql-server
    environment: 
      "MYSQL_USER": "test"
      "MYSQL_PASSWORD": "test"
      "MYSQL_DATABASE": "auction"
    ports:
      - "3306:3306"
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      "RABBITMQ_DEFAULT_VHOST": "delivery-vm"
    ports:
      - "15672:15672"
      - "5672:5672"