DROP TABLE IF EXISTS `User`;
DROP TABLE IF EXISTS `Article`;

CREATE TABLE `User` (
	id INT AUTO_INCREMENT,
	login VARCHAR(255),
	PRIMARY KEY(id)
);

CREATE TABLE `Article` (
	id INT AUTO_INCREMENT,
	name VARCHAR(255),
	PRIMARY KEY(id)
);